import type { DemoMap } from "../../kit/types";

/** Navigation · 导航: effect id → lazily loaded demo. */
export const demos: DemoMap = {
  "navigation.tab-indicator": () => import("./tab-indicator"),
  "navigation.segmented-thumb": () => import("./segmented-thumb"),
  "navigation.elastic-underline": () => import("./elastic-underline"),
  "navigation.gooey-tab": () => import("./gooey-tab"),
  "navigation.spotlight-tab": () => import("./spotlight-tab"),
  "navigation.hop-dot-tab": () => import("./hop-dot-tab"),
  "navigation.trace-tab": () => import("./trace-tab"),
  "navigation.collapsing-tab-bar": () => import("./collapsing-tab-bar"),
  "navigation.notch-tab-bar": () => import("./notch-tab-bar"),
  "navigation.search-tab-morph": () => import("./search-tab-morph"),
  "navigation.ripple-tab-bar": () => import("./ripple-tab-bar"),
  "navigation.page-dots": () => import("./page-dots"),
  "navigation.number-pager": () => import("./number-pager"),
  "navigation.timer-dots": () => import("./timer-dots"),
  "navigation.scrolling-dots": () => import("./scrolling-dots"),
  "navigation.side-drawer-3d": () => import("./side-drawer-3d"),
  "navigation.sidebar-rail": () => import("./sidebar-rail"),
  "navigation.parallax-drawer": () => import("./parallax-drawer"),
  "navigation.elastic-drawer": () => import("./elastic-drawer"),
  "navigation.popout-drawer": () => import("./popout-drawer"),
  "navigation.push-parallax": () => import("./push-parallax"),
  "navigation.bottom-sheet": () => import("./bottom-sheet"),
  "navigation.stacked-sheets": () => import("./stacked-sheets"),
  "navigation.fade-through": () => import("./fade-through"),
  "navigation.floating-sheet": () => import("./floating-sheet"),
  "navigation.radial-menu": () => import("./radial-menu"),
  "navigation.context-popover": () => import("./context-popover"),
  "navigation.context-menu-lift": () => import("./context-menu-lift"),
  "navigation.fold-menu": () => import("./fold-menu"),
  "navigation.overlay-menu": () => import("./overlay-menu"),
  "navigation.step-progress": () => import("./step-progress"),
  "navigation.dock-magnify": () => import("./dock-magnify"),
};
