import type { DemoMap } from "../../kit/types";

/** Buttons · 按钮: effect id → lazily loaded demo. */
export const demos: DemoMap = {
  "buttons.press-scale": () => import("./press-scale"),
  "buttons.magnetic": () => import("./magnetic"),
  "buttons.ink-ripple": () => import("./ink-ripple"),
  "buttons.depth-press": () => import("./depth-press"),
  "buttons.jelly-press": () => import("./jelly-press"),
  "buttons.soft-press": () => import("./soft-press"),
  "buttons.echo-press": () => import("./echo-press"),
  "buttons.stack-press": () => import("./stack-press"),
  "buttons.label-roll": () => import("./label-roll"),
  "buttons.like-burst": () => import("./like-burst"),
  "buttons.like-thumb": () => import("./like-thumb"),
  "buttons.like-liquid": () => import("./like-liquid"),
  "buttons.like-float": () => import("./like-float"),
  "buttons.like-draw": () => import("./like-draw"),
  "buttons.like-flip": () => import("./like-flip"),
  "buttons.like-double-tap": () => import("./like-double-tap"),
  "buttons.hold-to-confirm": () => import("./hold-to-confirm"),
  "buttons.hold-ring": () => import("./hold-ring"),
  "buttons.hold-charge": () => import("./hold-charge"),
  "buttons.hold-trace": () => import("./hold-trace"),
  "buttons.hold-segments": () => import("./hold-segments"),
  "buttons.add-to-cart": () => import("./add-to-cart"),
  "buttons.shimmer": () => import("./shimmer"),
  "buttons.glow-border": () => import("./glow-border"),
  "buttons.neon-breath": () => import("./neon-breath"),
  "buttons.ember-glow": () => import("./ember-glow"),
  "buttons.plasma-glass": () => import("./plasma-glass"),
  "buttons.spotlight": () => import("./spotlight"),
  "buttons.repel-letters": () => import("./repel-letters"),
  "buttons.parallax-tilt": () => import("./parallax-tilt"),
  "buttons.elastic-blob": () => import("./elastic-blob"),
  "buttons.expand-actions": () => import("./expand-actions"),
  "buttons.follow-morph": () => import("./follow-morph"),
  "buttons.gooey-split": () => import("./gooey-split"),
  "buttons.pill-toolbar": () => import("./pill-toolbar"),
  "buttons.unfold-menu": () => import("./unfold-menu"),
  "buttons.orbit-actions": () => import("./orbit-actions"),
  "buttons.liquid-glass": () => import("./liquid-glass"),
  "buttons.bookmark-ribbon": () => import("./bookmark-ribbon"),
  "buttons.copy-flip": () => import("./copy-flip"),
  "buttons.approve-stamp": () => import("./approve-stamp"),
};
