import type { DemoMap } from "../../kit/types";

/** Text · 文字动效: effect id → lazily loaded demo. */
export const demos: DemoMap = {
  "text.numeric-counter": () => import("./numeric-counter"),
  "text.blur-reveal": () => import("./blur-reveal"),
  "text.wave": () => import("./wave"),
  "text.typewriter": () => import("./typewriter"),
  "text.rotating-words": () => import("./rotating-words"),
  "text.scramble": () => import("./scramble"),
  "text.shimmer": () => import("./shimmer"),
  "text.odometer": () => import("./odometer"),
  "text.split-flap": () => import("./split-flap"),
  "text.flip-in-3d": () => import("./flip-in-3d"),
  "text.highlighter": () => import("./highlighter"),
  "text.marquee": () => import("./marquee"),
  "text.synced-lyrics": () => import("./synced-lyrics"),
  "text.masked-lines": () => import("./masked-lines"),
  "text.circular-badge": () => import("./circular-badge"),
  "text.variable-weight": () => import("./variable-weight"),
  "text.slot-reel": () => import("./slot-reel"),
  "text.gravity-digits": () => import("./gravity-digits"),
  "text.count-up": () => import("./count-up"),
  "text.seven-segment": () => import("./seven-segment"),
  "text.elastic-letters": () => import("./elastic-letters"),
  "text.light-sweep": () => import("./light-sweep"),
  "text.tracking-in": () => import("./tracking-in"),
  "text.spring-chain": () => import("./spring-chain"),
  "text.squash-hop": () => import("./squash-hop"),
  "text.scribble-circle": () => import("./scribble-circle"),
  "text.neon-sign": () => import("./neon-sign"),
  "text.news-ticker": () => import("./news-ticker"),
  "text.word-drum": () => import("./word-drum"),
  "text.type-cycle": () => import("./type-cycle"),
};
