import type { DemoMap } from "../../kit/types";

/** Feedback · 反馈提示: effect id → lazily loaded demo. */
export const demos: DemoMap = {
  "feedback.toast": () => import("./toast"),
  "feedback.island-pill": () => import("./island-pill"),
  "feedback.success-check": () => import("./success-check"),
  "feedback.error-shake": () => import("./error-shake"),
  "feedback.copy-confirm": () => import("./copy-confirm"),
  "feedback.inline-validation": () => import("./inline-validation"),
  "feedback.confetti": () => import("./confetti"),
  "feedback.connection-banner": () => import("./connection-banner"),
  "feedback.badge-bounce": () => import("./badge-bounce"),
  "feedback.stacked-banners": () => import("./stacked-banners"),
  "feedback.undo-snackbar": () => import("./undo-snackbar"),
  "feedback.alert-pop": () => import("./alert-pop"),
  "feedback.coach-spotlight": () => import("./coach-spotlight"),
  "feedback.reaction-picker": () => import("./reaction-picker"),
  "feedback.pull-refresh": () => import("./pull-refresh"),
  "feedback.goo-refresh": () => import("./goo-refresh"),
  "feedback.sun-refresh": () => import("./sun-refresh"),
  "feedback.letter-refresh": () => import("./letter-refresh"),
  "feedback.dots-refresh": () => import("./dots-refresh"),
  "feedback.hinge-toast": () => import("./hinge-toast"),
  "feedback.morph-toast": () => import("./morph-toast"),
  "feedback.spark-burst": () => import("./spark-burst"),
  "feedback.level-up": () => import("./level-up"),
  "feedback.glitch-error": () => import("./glitch-error"),
  "feedback.limit-bounce": () => import("./limit-bounce"),
  "feedback.faceid-fail": () => import("./faceid-fail"),
  "feedback.streak-flame": () => import("./streak-flame"),
  "feedback.presence-ping": () => import("./presence-ping"),
  "feedback.floating-hearts": () => import("./floating-hearts"),
  "feedback.receding-sheet": () => import("./receding-sheet"),
  "feedback.tip-popover": () => import("./tip-popover"),
  "feedback.drop-alert": () => import("./drop-alert"),
};
