import type { DemoMap } from "../../kit/types";

/** Loading · 加载与进度: effect id → lazily loaded demo. */
export const demos: DemoMap = {
  "loading.load-button": () => import("./load-button"),
  "loading.download-button": () => import("./download-button"),
  "loading.arc-spinner": () => import("./arc-spinner"),
  "loading.dot-bounce": () => import("./dot-bounce"),
  "loading.orbit-dots": () => import("./orbit-dots"),
  "loading.activity-petals": () => import("./activity-petals"),
  "loading.story-bars": () => import("./story-bars"),
  "loading.blur-up": () => import("./blur-up"),
  "loading.skeleton-shimmer": () => import("./skeleton-shimmer"),
  "loading.audio-wave": () => import("./audio-wave"),
  "loading.pulse-rings": () => import("./pulse-rings"),
  "loading.square-grid": () => import("./square-grid"),
  "loading.ai-generating": () => import("./ai-generating"),
  "loading.glow-bar": () => import("./glow-bar"),
  "loading.progress-ring": () => import("./progress-ring"),
  "loading.liquid-fill": () => import("./liquid-fill"),
  "loading.indeterminate-bar": () => import("./indeterminate-bar"),
  "loading.gooey-orbit": () => import("./gooey-orbit"),
  "loading.gyroscope": () => import("./gyroscope"),
  "loading.flip-tile": () => import("./flip-tile"),
  "loading.infinity-comet": () => import("./infinity-comet"),
  "loading.heartbeat": () => import("./heartbeat"),
  "loading.segment-bar": () => import("./segment-bar"),
  "loading.liquid-bar": () => import("./liquid-bar"),
  "loading.tooltip-bar": () => import("./tooltip-bar"),
  "loading.candy-stripes": () => import("./candy-stripes"),
  "loading.tick-ring": () => import("./tick-ring"),
  "loading.install-pie": () => import("./install-pie"),
  "loading.elastic-ring": () => import("./elastic-ring"),
  "loading.ring-to-check": () => import("./ring-to-check"),
  "loading.dash-flow-ring": () => import("./dash-flow-ring"),
  "loading.fill-button": () => import("./fill-button"),
  "loading.dots-button": () => import("./dots-button"),
  "loading.trace-button": () => import("./trace-button"),
  "loading.breathing-skeleton": () => import("./breathing-skeleton"),
  "loading.mosaic-resolve": () => import("./mosaic-resolve"),
};
