import type { DemoMap } from "../../kit/types";

/** Gestures · 手势 (first half, gestures-a): effect id → lazily loaded demo. */
export const demos: DemoMap = {
  "gestures.rubber-band": () => import("./rubber-band"),
  "gestures.fling-inertia": () => import("./fling-inertia"),
  "gestures.pip-snap": () => import("./pip-snap"),
  "gestures.jelly-stretch": () => import("./jelly-stretch"),
  "gestures.pinch-rotate": () => import("./pinch-rotate"),
  "gestures.swipe-actions": () => import("./swipe-actions"),
  "gestures.drag-reorder": () => import("./drag-reorder"),
  "gestures.spring-chain": () => import("./spring-chain"),
  "gestures.charge-burst": () => import("./charge-burst"),
  "gestures.drag-dismiss": () => import("./drag-dismiss"),
  "gestures.slide-to-confirm": () => import("./slide-to-confirm"),
  "gestures.magnifier-loupe": () => import("./magnifier-loupe"),
  "gestures.gooey-blobs": () => import("./gooey-blobs"),
  "gestures.verlet-rope": () => import("./verlet-rope"),
  "gestures.newtons-cradle": () => import("./newtons-cradle"),
  "gestures.photo-viewer": () => import("./photo-viewer"),
  "gestures.magnetic-snap": () => import("./magnetic-snap"),
  "gestures.elastic-tether": () => import("./elastic-tether"),
  "gestures.pendulum-swing": () => import("./pendulum-swing"),
  "gestures.gravity-toss": () => import("./gravity-toss"),
  "gestures.detent-sheet": () => import("./detent-sheet"),
  "gestures.coil-spring": () => import("./coil-spring"),
  "gestures.orbit-slingshot": () => import("./orbit-slingshot"),
  "gestures.swipe-complete": () => import("./swipe-complete"),
  "gestures.staged-swipe": () => import("./staged-swipe"),
  "gestures.drag-select": () => import("./drag-select"),
  "gestures.pinch-grid": () => import("./pinch-grid"),
  "gestures.pinch-open": () => import("./pinch-open"),
  "gestures.stretch-slide": () => import("./stretch-slide"),
  "gestures.notch-slide": () => import("./notch-slide"),
  "gestures.arc-slide": () => import("./arc-slide"),
  "gestures.pull-cord": () => import("./pull-cord"),
};
