import SwiftUI

enum ButtonEffects {
    static let all: [Effect] = [
        .buttonsPressScale,
        .buttonsMagnetic,
        .buttonsInkRipple,
        .buttonsDepthPress,
        .buttonsJellyPress,
        .buttonsSoftPress,
        .buttonsEchoPress,
        .buttonsStackPress,
        .buttonsLikeBurst,
        .buttonsLikeThumb,
        .buttonsLikeLiquid,
        .buttonsLikeFloat,
        .buttonsLikeDraw,
        .buttonsLikeFlip,
        .buttonsLikeDoubleTap,
        .buttonsHoldToConfirm,
        .buttonsHoldRing,
        .buttonsHoldCharge,
        .buttonsHoldTrace,
        .buttonsHoldSegments,
        .buttonsAddToCart,
        .buttonsShimmer,
        .buttonsGlowBorder,
        .buttonsNeonBreath,
        .buttonsEmberGlow,
        .buttonsPlasmaGlass,
        .buttonsSpotlight,
        .buttonsRepelLetters,
        .buttonsParallaxTilt,
        .buttonsElasticBlob,
        .buttonsExpandActions,
        .buttonsFollowMorph,
        .buttonsLabelRoll,
        .buttonsGooeySplit,
        .buttonsPillToolbar,
        .buttonsUnfoldMenu,
        .buttonsOrbitActions,
        .buttonsLiquidGlass,
        .buttonsBookmarkRibbon,
        .buttonsCopyFlip,
        .buttonsApproveStamp,
    ]
}
