import type { DemoMap } from "../../kit/types";

/** Showcase · 质感交互精选: effect id → lazily loaded demo. */
export const demos: DemoMap = {
  "showcase.save-burst": () => import("./save-burst"),
  "showcase.slide-to-start": () => import("./slide-to-start"),
  "showcase.speed-line": () => import("./speed-line"),
  "showcase.fresh-snow": () => import("./fresh-snow"),
  "showcase.board-card": () => import("./board-card"),
  "showcase.best-line": () => import("./best-line"),
  "showcase.photo-play": () => import("./photo-play"),
  "showcase.spots-grid": () => import("./spots-grid"),
  "showcase.go-countdown": () => import("./go-countdown"),
  "showcase.summit-badge": () => import("./summit-badge"),
  "showcase.altitude-ruler": () => import("./altitude-ruler"),
  "showcase.lift-status": () => import("./lift-status"),
  "showcase.heart-zone": () => import("./heart-zone"),
  "showcase.run-summary": () => import("./run-summary"),
  "showcase.weather-widget": () => import("./weather-widget"),
  "showcase.gear-checklist": () => import("./gear-checklist"),
  "showcase.fog-wipe": () => import("./fog-wipe"),
  "showcase.flight-path": () => import("./flight-path"),
  "showcase.trip-chips": () => import("./trip-chips"),
  "showcase.get-started": () => import("./get-started"),
  "showcase.destination-carousel": () => import("./destination-carousel"),
  "showcase.boarding-pass": () => import("./boarding-pass"),
  "showcase.pin-route": () => import("./pin-route"),
  "showcase.itinerary": () => import("./itinerary"),
  "showcase.transit-line": () => import("./transit-line"),
  "showcase.date-range": () => import("./date-range"),
  "showcase.polaroid-fan": () => import("./polaroid-fan"),
  "showcase.flip-clock": () => import("./flip-clock"),
  "showcase.now-playing": () => import("./now-playing"),
  "showcase.finance-card": () => import("./finance-card"),
  "showcase.sleep-timeline": () => import("./sleep-timeline"),
  "showcase.ev-charge": () => import("./ev-charge"),
};
